FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

ARG NEST_INTERNAL_API_BASE_URL=http://backend:3000
ENV NEST_INTERNAL_API_BASE_URL=$NEST_INTERNAL_API_BASE_URL

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
