FROM python:3.12-slim

WORKDIR /app

RUN pip install uv

COPY . .

RUN uv sync --frozen

EXPOSE 8800

CMD ["uv", "run", "uvicorn", "ragcore.main:app", "--host", "0.0.0.0", "--port", "8800", "--app-dir", "src"]